[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
runner = "qemu-system-aarch64 -M virt -cpu cortex-a53 -display none -serial stdio -global virtio-mmio.force-legacy=false -device virtio-rng-device -drive if=none,cache=directsync,file=test.img,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -kernel"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
